### ISSUE TITLE
Support multiple separators

### ISSUE THREAD

**Issue by aekiss** [COSIMA/make_diag_table#7]
Sometimes we want an alternative separator (e.g. no separator) between particular components - e.g. see https://github.com/COSIMA/access-om3/issues/190#issuecomment-2252030909 - how to implement this?

**Comment by aekiss** [comment]
It would be nice to modify `make_diag_table.py` so that this behaviour can be set as an option via `diag_table_source.yaml`.

Also, perhaps we can generalise by allowing `file_name_separator` to be an array of alternative separators (in this case `['.', '']`) and specify when to apply which separator?

Even neater, how about supporting this yaml format, where `file_name` can contain arrays whose names specify the separator to be applied before each element?

```yaml
    file_name:  # file name (without trailing ".nc") is constructed from these components,
    # separated by file_name_separator, as per https://github.com/COSIMA/access-om2/issues/185
    # All these components (other than field_name) must be names that exist in global_defaults.
    # If file_name_date or file_name_date_section are used, it must be the last item.
        - "_":
            - file_name_prefix
            - file_name_dimension
            - field_name  # substituted by field name in diag_table section below
            - output_freq
        - "":
            - output_freq_units
        - "_":
            - reduction_method
            - file_name_date
```

**Comment by aekiss** [comment]
This actually makes `file_name_separator` redundant, but we should retain it for backward compatability. Perhaps the rule should be: string items in `file_name` are separated by `file_name_separator`, but keys whose values are arrays have the array elements separated by the array key as above. With this approach we could write

```yaml
     file_name_separator: "-"  # used to separate filename components; best not to use "_" to avoid confusion with fields and dates
     file_name:  # file name (without trailing ".nc") is constructed from these components,
    # separated by file_name_separator, as per https://github.com/COSIMA/access-om2/issues/185
    # All these components (other than field_name) must be names that exist in global_defaults.
    # If file_name_date or file_name_date_section are used, it must be the last item.
        - file_name_prefix
        - file_name_dimension
        - field_name  # substituted by field name in diag_table section below
        - output_freq
        - "":
           - output_freq_units
        - reduction_method
        - file_name_date
```
meaning all elements except `output_freq_units` are separated by `file_name_separator`.
